name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elementary/docker:unstable

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        apt update
        apt install -y libgranite-dev libgtk-3-dev libvala-dev libvte-2.91-dev libwebkit2gtk-4.0-dev meson valac wget librsvg2-bin appstream elementary-theme elementary-icon-theme libgtk-3-common
    - name: Build
      env:
        DESTDIR: out
      run: |
        meson build
        ninja -C build
        ninja -C build install
    - name: AppImage
      run: |
        APPDIR=$(readlink -f appdir) # Why is this needed?
        DESTDIR="$APPDIR" ninja -C build install
        wget -c https://github.com/$(wget -q https://github.com/probonopd/go-appimage/releases -O - | grep "appimagetool-.*-x86_64.AppImage" | head -n 1 | cut -d '"' -f 2)
        chmod +x appimagetool-*.AppImage
        # mkdir -p "$APPDIR"/usr/share/icons/hicolor/256x256/apps/
        # rsvg-convert -w 256 -h 256 "$APPDIR"/usr/share/icons/hicolor/scalable/apps/com.github.akiraux.akira.svg > "$APPDIR"/usr/share/icons/hicolor/256x256/apps/com.github.akiraux.akira.png
        find "$APPDIR"
        # mkdir -p "$APPDIR"/usr/share/glib-2.0/schemas/ ; cp /usr/share/glib-2.0/schemas/org.gtk.Settings.*.xml "$APPDIR"/usr/share/glib-2.0/schemas/
        ./appimagetool-*.AppImage -s deploy "$APPDIR"/usr/share/applications/*.desktop --appimage-extract-and-run # Bundle EVERYTHING
        sed -i -e 's|/usr||g' "$APPDIR"/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache # FIXME in https://github.com/probonopd/go-appimage
        ( cd "$APPDIR"/usr/share/mime/ ; ln -s /usr/share/mime/mime.cache . ) # FIXME in https://github.com/probonopd/go-appimage; https://github.com/probonopd/go-appimage/issues/58#issuecomment-675010671
        # mkdir -p "$APPDIR"/usr/share/icons ; cp -r /usr/share/icons/elementary "$APPDIR"/usr/share/icons/ # https://github.com/akiraux/Akira/issues/3#issuecomment-674544807 and https://github.com/probonopd/go-appimage/blob/c522796229a3669afdf8b4870b045b597332c5a2/src/appimagetool/appdirtool.go#L715-L722
        # mkdir -p "$APPDIR"/usr/share/themes ; cp -r /usr/share/themes/elementary "$APPDIR"/usr/share/themes/ # https://github.com/akiraux/Akira/issues/3#issuecomment-674544807
        rm -rf "$APPDIR"/usr/share/themes/Default ; sed -i -e 's|Default|elementary|g' "$APPDIR"/AppRun # Use the elementary theme rather than the Gtk Default theme
        ./appimagetool-*.AppImage "$APPDIR" --appimage-extract-and-run # turn AppDir into AppImage
    - name: Release AppImage
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: AppImage
        automatic_release_tag: continuous
        prerelease: true
        draft: false
        files: |
          slack*.AppImage*
        repo_token: ${{ secrets.GITHUB_TOKEN }}


  lint:

    runs-on: ubuntu-latest
    
    container:
      image: valalang/lint
      
    steps:
    - uses: actions/checkout@v1
    - name: Lint
      run: io.elementary.vala-lint -d .
